// Generated by CoffeeScript 1.3.3
var fs, wrench;

fs = require('fs');

wrench = require('wrench');

module.exports = function(proj, gen) {
  var dest, dir, _i, _len, _ref, _results;
  _ref = ['images', 'javascripts', 'stylesheets', 'ico', 'img', 'js', 'css'];
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    dir = _ref[_i];
    try {
      dest = "" + gen + "/" + dir;
      fs.mkdirSync(dest);
      wrench.copyDirSyncRecursive("" + proj + "/" + dir, dest);
      _results.push(console.log('copied' + dest));
    } catch (err) {

    }
  }
  return _results;
};
