// Generated by CoffeeScript 1.3.3
var Page, assets, checkexists, fs, misc, wrench;

fs = require('fs');

wrench = require('wrench');

assets = require('./assets');

misc = require('./misc');

Page = require('./page');

checkexists = function(name, cb) {
  return fs.stat(name, function(err, stat) {
    return cb(err != null ? false : true);
  });
};

module.exports = function(proj, cb) {
  var gen;
  if (proj == null) {
    proj = '.';
  }
  gen = "" + proj + "/gen";
  return checkexists(gen, function(exists) {
    if (exists) {
      wrench.rmdirSyncRecursive(gen);
    }
    fs.mkdirSync(gen);
    (new Page()).all(gen, proj);
    assets(proj, gen);
    misc(proj, gen);
    console.log('Successfully Generated Static Site in the gen folder...');
    if (cb != null) {
      return cb(null, 'success');
    }
  });
};
