// Generated by CoffeeScript 1.3.3
var app, flatiron;

flatiron = require('flatiron');

require('pkginfo')(module);

app = flatiron.app;

app.version = exports.version;

app.use(flatiron.plugins.cli, {
  dir: __dirname,
  usage: ["Bam v" + app.version, "Easiest Static Site Generator on the Planet", "", "bam new [foo] [template]", "cd [foo]", "", "# run in dev mode", "bam run", "", "# generate site", "bam gen", "", "# test gen site", "bam serve"],
  version: true
});

app.cmd('version', function() {
  return console.log('BAM v' + app.version);
});

app.cmd('new', require('./new'));

app.cmd('run', require('./run'));

app.cmd('gen', require('./gen'));

app.cmd('serve', require('./serve'));

app.start();
