// Generated by CoffeeScript 1.3.3
var buildFiles, buildLayout, buildProjectFolder, copy, copyAssets, coreFiles, eco, fs, log, project, renderTemplate, template, wrench;

eco = require('eco');

fs = require('fs');

wrench = require('wrench');

log = console.log;

coreFiles = ['server.js', 'package.json', 'robots.txt', '404.html'];

project = null;

template = null;

module.exports = function(proj, tmpl, cb) {
  var _ref;
  if (proj == null) {
    proj = null;
  }
  if (typeof tmpl === 'function') {
    cb = tmpl;
    tmpl = null;
  }
  if (proj == null) {
    return console.log('Project Name Required!');
  }
  _ref = [proj, tmpl || "skeleton"], project = _ref[0], template = _ref[1];
  log('Building Project Folder...');
  return buildProjectFolder(function() {
    if (process.env.NODE_ENV === 'debug') {
      log('Building Files...');
    }
    return buildFiles(function() {
      if (process.env.NODE_ENV === 'debug') {
        log('Copying Assests...');
      }
      return copyAssets(function() {
        if (process.env.NODE_ENV === 'debug') {
          log('Building Layout...');
        }
        return buildLayout(function() {
          log('Done....');
          return cb(null, 'Done');
        });
      });
    });
  });
};

buildProjectFolder = function(cb) {
  return fs.exists("./" + project, function(exists) {
    if (exists) {
      wrench.rmdirSyncRecursive("./" + project);
    }
    fs.mkdirSync(project, 0x1ed);
    return cb(null);
  });
};

buildFiles = function(cb) {
  var tmp, _i, _len;
  for (_i = 0, _len = coreFiles.length; _i < _len; _i++) {
    tmp = coreFiles[_i];
    renderTemplate(tmp, project, {
      title: project
    });
  }
  return cb(null);
};

buildLayout = function(cb) {
  var tmp;
  tmp = fs.readFileSync(__dirname + ("/../templates/" + template + "/layout.html.eco"), "utf8");
  fs.writeFileSync("./" + project + "/layout.html", eco.render(tmp, {
    title: project
  }));
  return cb(null);
};

copyAssets = function(cb) {
  var copy, dir, _i, _len, _ref;
  copy = function(dir) {
    return fs.exists("" + __dirname + "/../templates/" + template + "/" + dir, function(exists) {
      try {
        fs.mkdirSync("./" + project + "/" + dir);
        return wrench.copyDirSyncRecursive("" + __dirname + "/../templates/" + template + "/" + dir, "./" + project + "/" + dir);
      } catch (err) {
        if (process.env.NODE_ENV === 'debug') {
          return console.log(err.message);
        }
      }
    });
  };
  _ref = ['images', 'javascripts', 'stylesheets', 'ico', 'img', 'js', 'css', 'pages'];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    dir = _ref[_i];
    copy(dir);
  }
  return cb(null);
};

renderTemplate = function(name, data) {
  var tmp;
  if (data == null) {
    data = {};
  }
  tmp = fs.readFileSync(__dirname + ("/../templates/" + name + ".eco"), "utf8");
  fs.writeFileSync("./" + project + "/" + name, eco.render(tmp, data));
  return true;
};

copy = function(src, dest) {
  var destFile;
  destFile = fs.createWriteStream(dest);
  fs.createReadStream(src).pipe(destFile);
  return true;
};
