// Generated by CoffeeScript 1.3.3
var Page, filed, fs, http, log, url;

http = require('http');

url = require('url');

fs = require('fs');

filed = require('filed');

log = console.log;

Page = require('./page');

module.exports = function(port, proj) {
  var server;
  if (proj == null) {
    proj = '.';
  }
  server = http.createServer(function(req, resp) {
    var pathname;
    pathname = url.parse(req.url).pathname;
    if (pathname === '/') {
      pathname = '/index.html';
    }
    try {
      if (/^\/(stylesheets|images|javascripts|css|img|js)/.test(pathname)) {
        return filed("." + pathname).pipe(resp);
      } else {
        pathname = pathname.replace('.html', '');
        resp.writeHead(200, 'Content-Type: text/html');
        return resp.end((new Page(pathname)).render());
      }
    } catch (err) {
      log("Unable to locate file " + pathname);
      return filed('./404.html').pipe(resp);
    }
  });
  try {
    return server.listen(port || 3000, function() {
      return log("Server running on port " + (port || 3000));
    });
  } catch (err) {
    return log('Not able to detect BAM application');
  }
};
