// Generated by CoffeeScript 1.3.3
var eco, filed, fs, ghm, http, log, renderHtml, renderMarkdown, renderTemplate, url, wrench;

http = require('http');

url = require('url');

eco = require('eco');

ghm = require('github-flavored-markdown');

fs = require('fs');

filed = require('filed');

log = console.log;

wrench = require('wrench');

renderMarkdown = function(name) {
  var md;
  md = fs.readFileSync("./pages" + name + ".md").toString();
  return ghm.parse(md);
};

renderHtml = function(name) {
  return fs.readFileSync("./pages" + name + ".html").toString();
};

renderTemplate = function(body) {
  var template;
  if (body == null) {
    body = "";
  }
  template = fs.readFileSync("./layout.html", "utf8");
  return eco.render(template, {
    body: body
  });
};

module.exports = function(port, proj) {
  var server;
  if (proj == null) {
    proj = '.';
  }
  server = http.createServer(function(req, resp) {
    var body, ext, index, page, pages, pathname, _i, _len;
    pages = wrench.readdirSyncRecursive('pages');
    pathname = url.parse(req.url).pathname;
    if (pathname === '/') {
      pathname = '/index.html';
    }
    try {
      if (pathname.match(/^\/(stylesheets|images|javascripts|css|img|js)/)) {
        return filed("." + pathname).pipe(resp);
      } else {
        pathname = pathname.replace('.html', '');
        for (index = _i = 0, _len = pages.length; _i < _len; index = ++_i) {
          page = pages[index];
          if ('/' + (page != null ? page.split('.')[0] : void 0) === pathname) {
            ext = page.split('.')[1];
          }
        }
        if (ext === 'html') {
          body = renderHtml(pathname);
        } else {
          body = renderMarkdown(pathname);
        }
        resp.writeHead(200, 'Content-Type: text/html');
        return resp.end(renderTemplate(body));
      }
    } catch (err) {
      console.log("Unable to locate file " + pathname);
      return filed('./404.html').pipe(resp);
    }
  });
  try {
    return server.listen(port || 3000, function() {
      return console.log("Server running on port " + (port || 3000));
    });
  } catch (err) {
    return console.log('Not able to detect BAM application');
  }
};
