// Generated by CoffeeScript 1.3.3
var filed, http, log, url, w3;

http = require('http');

url = require('url');

filed = require('filed');

w3 = require('w3');

log = console.log;

module.exports = function(proj) {
  if (proj == null) {
    proj = '.';
  }
  return w3(3000, './gen');
};
