// Generated by CoffeeScript 1.3.3
var cc;

cc = require('zeke');

module.exports = function() {
  cc.use(require('zeke-markdown'));
  cc.use({
    attach: function() {
      this.addModule('fs', 'fs');
      this.helpers['get'] = function(s) {
        return data.fs.readFileSync(s);
      };
      this.helpers['escape'] = function(html) {
        return html.replace(/</g, '&lt;').replace(/>/, '&gt;');
      };
      return this.helpers['jpg2'] = function(name) {
        return img({
          src: "http://" + name + ".jpg.to",
          style: 'max-height: 90%;max-width:90%'
        });
      };
    }
  });
  if (!cc.initialized) {
    cc.init();
  }
  return cc;
};
