// Generated by CoffeeScript 1.3.3
var cc;

cc = require('zeke');

module.exports = function() {
  cc.use(require('zeke-markdown'));
  cc.use(require('zeke-bootstrap'));
  cc.use(require('zeke-bam'));
  cc.use({
    attach: function() {
      this.addModule('fs', 'fs');
      return this.helpers['get'] = function(s) {
        return data.fs.readFileSync(s);
      };
    }
  });
  if (!cc.initialized) {
    cc.init();
  }
  return cc;
};
