// Generated by CoffeeScript 1.3.3
var fs;

fs = require('fs');

module.exports = function(src, dest) {
  var destFile;
  destFile = fs.createWriteStream(dest);
  fs.createReadStream(src).pipe(destFile);
  return true;
};
