// Generated by CoffeeScript 1.3.3
var eco, fs;

eco = require('eco');

fs = require('fs');

module.exports = function(name, data) {
  var tmp;
  if (data == null) {
    data = {};
  }
  tmp = fs.readFileSync(__dirname + ("/../../templates/" + name + ".eco"), "utf8");
  return eco.render(tmp, data);
};
