// Generated by CoffeeScript 1.3.3
var filed;

filed = require('filed');

module.exports = function(proj, gen) {
  var misc, _i, _len, _ref, _results;
  _ref = ['404.html', 'robots.txt'];
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    misc = _ref[_i];
    filed("" + proj + "/" + misc).pipe(filed("" + gen + "/" + misc));
    _results.push(console.log('copied' + ("" + gen + "/" + misc)));
  }
  return _results;
};
